spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: testdb
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

redis:
  database: prova-free-db
  password: G4gh20YpZOKHVR674mU3NHu9qeYBCokQ
  host: redis-18146.c277.us-east-1-3.ec2.cloud.redislabs.com
  port: 18146